### ISSUE TITLE
Cldr.List.to_tuple/1 is undefined

### ISSUE THREAD

**Issue by Zurga** [elixir-cldr/cldr_lists#3]
Thank you for the work on this package!
I am trying to install the Cldr.List provider in our project but I am greeted with the error in the title.

Here is the full stacktrace:
```
== Compilation error in file lib/bubble/cldr.ex ==
** (UndefinedFunctionError) function Bubble.Cldr.List.to_tuple/1 is undefined or private
    Bubble.Cldr.List.to_tuple(["+HH:mm", "-HH:mm"])
    lib/bubble/cldr.ex:1: anonymous fn/3 in :elixir_compiler_19.__MODULE__/1
    (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/bubble/cldr.ex:1: (module)
    /home/bubble/lib/bubble/cldr.ex:1: Cldr.Backend.Compiler.__before_compile__/1
```
I am using the following version of Cldr and other providers in my mix.exs:
```
      # internationalization
      {:ex_cldr, "~> 2.15.0"},
      {:ex_cldr_languages, "~> 0.2.0"},
      {:ex_cldr_dates_times, "~> 2.4.0"},
      {:ex_cldr_numbers, "~> 2.14.0"},
      {:ex_cldr_units, "~> 3.1.0"},
      {:ex_cldr_lists, "~> 2.5.0"}
```
And I have setup my App.Cldr as follows:
```
defmodule Bubble.Cldr do
  use Cldr,
    default_locale: "en",
    locales: ~w/en fr nl de es it pt/,
    data_dir: "cldr",
    opt_app: Bubble,
    providers: [Cldr.Language, Cldr.List, Cldr.Number, Cldr.DateTime, Cldr.Unit]
end
```
While writing this issue I changed the order of the providers and found that it does not crash when I set the providers in the following order:
 [Cldr.Language, Cldr.Number, Cldr.DateTime, Cldr.Unit, Cldr.List]

**Comment by kipcole9** [comment]
Thanks for the report, and for being kind enough to identify a workaround.  I will either (a) force a provider order to ensure this doesn't happen or (b) force compilation order - this would be preferred.

Since you have established a workaround for now I hope you're ok if I don't get to this until the weekend (I'll aim to resolve faster but that may not be possible).

**Comment by kipcole9** [comment]
Ah, turns out to be a different issue which is [fixed in this commit](https://github.com/elixir-cldr/cldr_dates_times/commit/7b043e816a755934a584806a96f1f9ecbac0d91f) to [ex_cldr_date_times](https://github.com/elixir-cldr/cldr_dates_times).

I have a new release of that library coming this weekend with some very cool interval formatting. I'll keep this issue open until I publish the new update.

**Comment by Zurga** [comment]
Thank you for the quick response and the fix. I am totally fine with the workaround for now :).
