### ISSUE TITLE
:format and :style option are both used 

### ISSUE THREAD

**Issue by Zurga** [elixir-cldr/cldr_lists#4]
Hi, 

When using the List.to_string!/3 function, the option :format is also taken into account, but the documentation states that only the :style option determines how the list should be formatted. When I look at https://github.com/elixir-cldr/cldr_lists/blob/v2.5.0/lib/cldr/list/backend.ex#L226 the format: option is still used. 

Maybe it would be a good solution to depricate the :format option and then completely switch to :style?

Kind regards,
Jim

**Comment by kipcole9** [comment]
Arrrghhhhh, I have gone backwards and forwards on this and you are right, I need to take a stand. I think `:format` is probably the way to go since in most of my libraries the format is either a predefined one (denoted by using an atom) or a free form one (using a binary). 

Thanks for pointing out the inconsistency of implementation and documentation. And thanks for using `cldr_lists` - it doesn't get as much love as the other libs but I think its quite cool :-)

**Comment by Zurga** [comment]
I am fine with either one you choose :).

The Cldr libraries are all really useful, thanks again for the time and effort you put into them. 
At the moment I am implementing a function at my job that spells out time in a 'human' fashion, e.g. "five and a half hours".
I am using the `cldr_calendars`, `cldr_units`, `cldr_number`, and `cldr_lists`, and I am very happy that these exist!

**Comment by kipcole9** [comment]
Published [ex_cldr_lists version 2.6.0](https://hex.pm/packages/ex_cldr_lists) with the following changelog:

### Enhancements

* Standardize on `:format` rather than `:style` for formatting options. This is part of an ongoing effort to standardise option naming across the CLDR libraries. Thanks to @Zurga for the collaboration. Closes #4.  This reverts the decision made in `ex_cldr_lists version 2.4.0`.

* Deprecates `Cldr.List.list_styles_for/2` in favour of `Cldr.List.list_formats_for/2`

* Updates to use `Cldr.locale_and_backend_from/{1, 2}` which normalizes extraction of backend and locale from parameters and options. As a result, also bump the minimum version of `ex_cldr_numbers` to `2.15`
